# Generated by Django 5.0.2 on 2024-04-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scam_type', models.CharField(max_length=100)),
                ('scam_source', models.CharField(max_length=255)),
                ('scam_date', models.DateTimeField(auto_now_add=True)),
                ('scam_description', models.CharField(max_length=2000)),
                ('scam_picture', models.ImageField(upload_to=None)),
                ('scam_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Panding', 'Panding'), ('Safe', 'Safe')], default='Pending', max_length=100)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
